language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
before_install:
- mvn clean
- git clone -b travis `git config --get remote.origin.url` target/travis
- cp target/travis/settings.xml ~/.m2/settings.xml
install: mvn install -DskipTests=true -Dgpg.skip=true
script: mvn verify
branches:
  only:
  - master
after_success:
- utilities/after_success.sh
env:
  global:
  - secure: p8x+e+O3UHhRZjoFTlT+oQSoyeeL2v7Xy7NKP23h8a/eHBBqU6hssvVRhGgy9sXl416qOyA3ZZ139N87MK0VzN45AR4FN+LriQKnI/7CsqC+rBRux7VKClpP7HjAFPhb6xdXO5E6CDHq5HN8CRQuFXHgU49/E2o+k49jSYySykEr1BpiEaSyUR0wctyBAihWKXqK2GgHu1atPg8lYSGtXfBCf/IVjGaHgXPK2XimuiNmLcFAm0DDzxx3Swt7e4U+mPjpHNDqIdBvPLqpZQx7YVHpFVlTHF4NmCDlP9MRANmw401/rVRC9bj71N/tXHzF44bxDoddpbrhhZUdZrqhWdccD8cnKOlT6WUXta7xrm63V+uhAAXwoQpregaEB+zZeikQKpmhkJRaqCesT3dUKxlw8yWz0Jj7pSJOjRmznUARfyKPYLBCQbaJ7BU4Ftl3avfNXYFfsEQU94ioGzs7LDwv/c07kuv/Xyg7UbfvpaXurHp711mFYZxL1UgR7+WYgSRJFA5IejQp1R4Ykc1/pGS0cvuUkE4M8Z/DMlTzsog8k4Azqs1Mh3FbK9q6j//0qFde3kexkJZEMA9smyeTMaizaIp6bD5uILjd8c7pLN+S6pBriDA+vkJ73cFtO8/75vggIQ2DgIozxHcId0g7OVx5HmPMEFYmoPJ7gTQm16I=
  - secure: "19G6KBLgnxjELh5HO998YU/+GVhvlOvVhwJZFxJpqcgjem1u3eQjwPsr3fAIFM20fy+S8+JoQaCUKJQ1taUlhr0YzKLuabdhe3DoT3NKUEoj5ORgwIjvWBqjEr72Lw9u2KRWdWP0oI/AOMYs95MlQ/E6HK6LDvbxl4qRneCzDBphYKg3XaUJhMiZozvERpTp2ZYuUhlhXxxzh0sz4kpcMc+Ee37F76qFLqIhqJQllpqVvNA0dg32dWaKhSYlzw/fcAg+0cbOj9nXl9LQPuCf4iS58CCHmhcUyqttEp16PuqCUc0mP505DjW3vuTQ1NdoM7eAdWAwB+zLhgVu/HOaKqYGncZkflc83cbNghvGCzCP4laJKynPW321SSyitV7zfC1D38CHMuaooniOfc3E7bPgxhD8+WYpgnIzEibPKOm5/a4ewaIwF07D8uGR7IogQKUj4z9vm/NnzkAcbemGiNGFaPAGtTVFxfa52k7TFCVm8et/tXaX3sjOwRzW69Qet0qvO6faaBrIbStPzze8Yrya40M0fIK9TJmm8ILFFgSWdgkd/zC8awwHgm/Z47UpqduYubZbpvqp0m1U1/2clvxRVOsgIxKKfJEhmgmnPOQJRmVyOPJT2gxWGx1Diqv0LBg2+ZfStzCYPQm/F44ttJ9mVPJCpY469FPN+CBYDf4="
