language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
before_install:
- mvn clean
- git clone -b travis `git config --get remote.origin.url` target/travis
- cp target/travis/settings.xml ~/.m2/settings.xml
install: mvn install -DskipTests=true -Dgpg.skip=true
script: mvn verify
branches:
  only:
  - master
after_success:
- utilities/after_success.sh
env:
  global:
  - secure: p8x+e+O3UHhRZjoFTlT+oQSoyeeL2v7Xy7NKP23h8a/eHBBqU6hssvVRhGgy9sXl416qOyA3ZZ139N87MK0VzN45AR4FN+LriQKnI/7CsqC+rBRux7VKClpP7HjAFPhb6xdXO5E6CDHq5HN8CRQuFXHgU49/E2o+k49jSYySykEr1BpiEaSyUR0wctyBAihWKXqK2GgHu1atPg8lYSGtXfBCf/IVjGaHgXPK2XimuiNmLcFAm0DDzxx3Swt7e4U+mPjpHNDqIdBvPLqpZQx7YVHpFVlTHF4NmCDlP9MRANmw401/rVRC9bj71N/tXHzF44bxDoddpbrhhZUdZrqhWdccD8cnKOlT6WUXta7xrm63V+uhAAXwoQpregaEB+zZeikQKpmhkJRaqCesT3dUKxlw8yWz0Jj7pSJOjRmznUARfyKPYLBCQbaJ7BU4Ftl3avfNXYFfsEQU94ioGzs7LDwv/c07kuv/Xyg7UbfvpaXurHp711mFYZxL1UgR7+WYgSRJFA5IejQp1R4Ykc1/pGS0cvuUkE4M8Z/DMlTzsog8k4Azqs1Mh3FbK9q6j//0qFde3kexkJZEMA9smyeTMaizaIp6bD5uILjd8c7pLN+S6pBriDA+vkJ73cFtO8/75vggIQ2DgIozxHcId0g7OVx5HmPMEFYmoPJ7gTQm16I=
  - secure: LAMvBHhWrFYmSX1GMigNVUd/acKU2SrVwjJbnpOCo5LH8yJ9p2wG3PAt2y+MqQALAA9TQXicfgyTYnH6BvlhaHYeNuG1VCEv6sZk+Mhr5TD3bytQgKLceXqfuMnvW9zZWYc7akxsNax8/08hXlkcgTr+akjZe+K4Ej1lM1EITKtNwSVGoZMLKetWTML37Z3yZFI49LOnJ4M5/K/27qJfoaLftzc7Y0YvkJ/VDdPvGondG+JJRepXyXK5IU67fqFqYp23trnu2C708kdTjUGpbOIuARoC4nEP8JhAf9jr7OqBJxRrKAytgRXGYXt/Bt46CY/q+345MODrdcXEowOzlAmzIeL2tmMdcrqlW7b94Df/8hGwfpcnKGNc/sPVNj2Cc5wPuvzDQuKCrFWdKGNSVg1D3QW90uM8/Sq0+yq2sDsigPDekZAbj8v6wUPFaVlCVlAtf5ynckwKMoMA/vEsz8U4nGslBgwNwwOJiDVxnVZagTKBOVE9HLBKadD4qdVb5eYM8Y08Geq061xMXjzwo7ojleHRQfnJLr5IjeLb7z1FOquhnsgfeEcZjrLUSAFeV++lgZo9eoFba0VU2XWWbgwoi5Ygmljv2NiFfjpC0yS0BjyGh87RUQUuyd8LQ/NVR48eeu+5aP0SmJbe5EnU7Ohw0HVAIAdqgbVH92YDKLw=
